# Generated by Django 3.0.3 on 2021-05-16 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
        ('chats', '0002_auto_20210516_1908'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser', name='user', field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),),
        migrations.AddField(
            model_name='notification', name='actor', field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),),
        migrations.AddField(
            model_name='notification', name='chat', field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.Chat'),),
        migrations.AddField(
            model_name='notification', name='connection', field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Connection'),),
        migrations.AddField(
            model_name='notification', name='collaborate_request', field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.CollaborateRequest'),),
        migrations.AddField(
            model_name='notification', name='member_joined', field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_joined',
                to=settings.AUTH_USER_MODEL),),
        migrations.AddField(
            model_name='notification', name='messages', field=models.ManyToManyField(
                blank=True, related_name='notifications_messages', to='chats.Message'),),
        migrations.AddField(
            model_name='notification', name='post', field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),),
        migrations.AddField(
            model_name='notification', name='post_messages', field=models.ManyToManyField(
                blank=True, related_name='notifications_post_messages', to='posts.PostMessage'),),
        migrations.AddField(
            model_name='notification', name='review', field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Review'),), ]
