# Generated by Django 3.0.3 on 2021-07-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_portalmember_donations_received_count'),
        ('notifications', '0002_auto_20210706_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portals.Portal'),
        ),
    ]
