# Generated by Django 3.0.3 on 2021-05-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210510_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ME', 'Messages'), ('NI', 'New invitation'), ('NC', 'New connection'), ('CR', 'New contribute request'), ('JM', 'Joined membership'), ('CA', 'Contribute request accepted'), ('PM', 'Post messages')], max_length=2),
        ),
    ]
