# Generated by Django 3.0.3 on 2021-01-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20210127_1742'),
        ('notifications', '0002_auto_20210126_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ME', 'Messages'), ('CO', 'Activity')], max_length=2),
        ),
    ]
