# Generated by Django 3.0.3 on 2021-05-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_auto_20210518_1502'),
        ('notifications', '0002_auto_20210516_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.Donation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ME', 'Messages'), ('NI', 'New invitation'), ('NC', 'New connection'), ('CR', 'New contribute request'), ('JM', 'Joined membership'), ('CA', 'Contribute request accepted'), ('PM', 'Post messages'), ('PF', 'Post finalized'), ('NR', 'New review'), ('ND', 'New donation')], max_length=2),
        ),
    ]
