# Generated by Django 3.0.3 on 2021-04-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_requesttoconnect'),
        ('notifications', '0002_auto_20210419_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Connection'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ME', 'Messages'), ('NI', 'New invitation'), ('NC', 'New connection')], max_length=2),
        ),
    ]
