# Generated by Django 3.0.3 on 2021-05-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210529_1419'),
        ('notifications', '0003_auto_20210529_1835'),
    ]

    operations = [
    ]
