# Generated by Django 3.0.3 on 2021-01-11 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_auto_20210111_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user_notification', to='notifications.Notification'),
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
