# Generated by Django 3.0.3 on 2021-05-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210506_2157'),
        ('notifications', '0003_auto_20210507_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contribute_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.ContributeRequest'),
        ),
    ]
