# Generated by Django 3.0.3 on 2021-05-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210515_1606'),
        ('notifications', '0004_auto_20210511_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Rating'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ME', 'Messages'), ('NI', 'New invitation'), ('NC', 'New connection'), ('CR', 'New contribute request'), ('JM', 'Joined membership'), ('CA', 'Contribute request accepted'), ('PM', 'Post messages'), ('PF', 'Post finalized'), ('NR', 'New review')], max_length=2),
        ),
    ]
