# Generated by Django 3.0.3 on 2021-01-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20210111_1719'),
        ('notifications', '0005_auto_20210111_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='notifications_messages', to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ME', 'Messages')], max_length=2),
        ),
    ]
