# Generated by Django 3.0.3 on 2021-01-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('chats', '0002_auto_20210121_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
