# Generated by Django 3.0.3 on 2021-03-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_messagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefile',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.Chat'),
        ),
    ]
