# Generated by Django 3.0.3 on 2021-06-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='Portal name')),
                ('url', models.SlugField(max_length=40)),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='about client')),
                ('logo', models.ImageField(blank=True, max_length=500, null=True, upload_to='portals/logos/', verbose_name='client logo')),
                ('donations_enabled', models.BooleanField(default=False)),
                ('all_users_count', models.IntegerField(default=0)),
                ('admins_count', models.IntegerField(default=0)),
                ('managers_count', models.IntegerField(default=0)),
                ('users_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('created_posts_count', models.IntegerField(default=0)),
                ('created_active_posts_count', models.IntegerField(default=0)),
                ('created_solved_posts_count', models.IntegerField(default=0)),
                ('collaborated_posts_count', models.IntegerField(default=0)),
                ('collaborated_active_posts_count', models.IntegerField(default=0)),
                ('collaborated_solved_posts_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='Role name')),
                ('role', models.CharField(choices=[('AD', 'Administrator'), ('MA', 'Managers'), ('BA', 'Basic')], max_length=2)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.Portal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portal',
            name='users',
            field=models.ManyToManyField(through='portals.Role', to=settings.AUTH_USER_MODEL, verbose_name='room_participants'),
        ),
    ]
