# Generated by Django 3.0.3 on 2021-06-14 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='Portal name')),
                ('url', models.SlugField(max_length=40)),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='about client')),
                ('logo', models.ImageField(blank=True, max_length=500, null=True, upload_to='portals/logos/', verbose_name='client logo')),
                ('donations_enabled', models.BooleanField(default=False)),
                ('all_users_count', models.IntegerField(default=0)),
                ('admins_count', models.IntegerField(default=0)),
                ('managers_count', models.IntegerField(default=0)),
                ('users_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('created_posts_count', models.IntegerField(default=0)),
                ('created_active_posts_count', models.IntegerField(default=0)),
                ('created_solved_posts_count', models.IntegerField(default=0)),
                ('collaborated_posts_count', models.IntegerField(default=0)),
                ('collaborated_active_posts_count', models.IntegerField(default=0)),
                ('collaborated_solved_posts_count', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortalMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('role', models.CharField(choices=[('AD', 'Administrator'), ('MA', 'Managers'), ('BA', 'Basic')], default='BA', max_length=2)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.Portal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portal',
            name='users',
            field=models.ManyToManyField(through='portals.PortalMember', to=settings.AUTH_USER_MODEL, verbose_name='room_participants'),
        ),
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('to_be_cancelled', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('payment_issue', models.BooleanField(default=False)),
                ('coupon', models.CharField(blank=True, max_length=100, null=True)),
                ('current_period_end', models.IntegerField(blank=True, default=0)),
                ('plan_type', models.CharField(choices=[('SI', 'Silver'), ('GO', 'Gold'), ('PL', 'Platinum')], max_length=2)),
                ('plan_unit_amount', models.FloatField(blank=True, null=True)),
                ('plan_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('plan_price_label', models.CharField(blank=True, max_length=100, null=True)),
                ('interval', models.CharField(blank=True, choices=[('MO', 'Monthly'), ('YE', 'Yearly')], max_length=2, null=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.Portal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('paid', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_pdf', models.CharField(blank=True, max_length=150, null=True)),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.Portal')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.PlanSubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
