# Generated by Django 3.0.3 on 2021-07-11 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmember',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.Portal'),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portal',
            name='members',
            field=models.ManyToManyField(through='portals.PortalMember', to=settings.AUTH_USER_MODEL, verbose_name='room_participants'),
        ),
        migrations.AddField(
            model_name='portal',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.Portal'),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planpayment',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portals.Portal'),
        ),
        migrations.AddField(
            model_name='planpayment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.PlanSubscription'),
        ),
        migrations.AddField(
            model_name='planpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_portal', to='portals.Portal'),
        ),
    ]
