# Generated by Django 3.0.3 on 2021-07-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210716_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='initial_karma_amount',
            field=models.IntegerField(default=1000),
        ),
    ]
