# Generated by Django 3.0.3 on 2021-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210706_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmember',
            name='donations_made_count',
            field=models.IntegerField(default=0),
        ),
    ]
