# Generated by Django 3.0.3 on 2021-07-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210711_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='communities_count',
            field=models.IntegerField(default=0),
        ),
    ]
