# Generated by Django 3.0.3 on 2021-06-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20210615_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='managers_count',
            new_name='moderators_count',
        ),
        migrations.AlterField(
            model_name='portalmember',
            name='role',
            field=models.CharField(choices=[('AD', 'Administrator'), ('MO', 'Moderators'), ('BA', 'Basic')], default='BA', max_length=2),
        ),
    ]
