# Generated by Django 3.0.3 on 2021-06-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_auto_20210619_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='all_users_count',
            new_name='base_users_count',
        ),
        migrations.AlterField(
            model_name='portalmember',
            name='role',
            field=models.CharField(choices=[('AD', 'Administrator'), ('MO', 'Moderators'), ('BA', 'Base')], default='BA', max_length=2),
        ),
    ]
