# Generated by Django 3.0.3 on 2021-07-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_portal_communities_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='collaborated_active_posts_count',
            new_name='active_posts_count',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='collaborated_posts_count',
            new_name='solved_posts_count',
        ),
        migrations.RemoveField(
            model_name='community',
            name='collaborated_solved_posts_count',
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_active_posts_count',
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_posts_count',
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_solved_posts_count',
        ),
    ]
