# Generated by Django 3.0.3 on 2021-06-19 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_auto_20210619_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='portal',
            name='admins_count',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='base_users_count',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='moderators_count',
        ),
        migrations.RemoveField(
            model_name='portalmember',
            name='role',
        ),
        migrations.AddField(
            model_name='portalmember',
            name='roles',
            field=models.ManyToManyField(to='portals.PortalRole'),
        ),
    ]
