# Generated by Django 3.0.3 on 2021-06-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_auto_20210619_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalmember',
            name='roles',
        ),
        migrations.AddField(
            model_name='portalmember',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='is_base_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PortalRole',
        ),
    ]
