# Generated by Django 3.0.3 on 2021-06-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_auto_20210620_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalmember',
            name='is_administrator',
        ),
        migrations.RemoveField(
            model_name='portalmember',
            name='is_base_user',
        ),
        migrations.RemoveField(
            model_name='portalmember',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='portalmember',
            name='type',
            field=models.CharField(choices=[('AD', 'Administrator'), ('MA', 'Manager'), ('BA', 'Basic')], default='BA', max_length=2),
        ),
    ]
