# Generated by Django 3.0.3 on 2021-06-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_auto_20210622_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='administrators_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portal',
            name='base_users_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portal',
            name='managers_count',
            field=models.IntegerField(default=0),
        ),
    ]
