# Generated by Django 3.0.3 on 2021-06-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0008_auto_20210622_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='about portal'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='portals/logos/', verbose_name='portal logo'),
        ),
    ]
