# Generated by Django 3.0.3 on 2021-06-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0009_auto_20210622_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portalmember',
            old_name='type',
            new_name='role',
        ),
    ]
