# Generated by Django 3.0.3 on 2021-06-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0010_auto_20210623_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='free_trial_expiration',
            field=models.DateTimeField(blank=True, help_text='Date time on the free tiral expiration.', null=True, verbose_name='free trial expiration at'),
        ),
        migrations.AddField(
            model_name='portal',
            name='free_trial_invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portal',
            name='interval',
            field=models.CharField(blank=True, choices=[('MO', 'Monthly'), ('YE', 'Yearly')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='is_free_trial',
            field=models.BooleanField(default=False, help_text='Set to true when the seller is in free trial.', verbose_name='free trial'),
        ),
        migrations.AddField(
            model_name='portal',
            name='passed_free_trial_once',
            field=models.BooleanField(default=False, help_text='Set to true when the seller alreay passed free trial once.', verbose_name='passed free trial'),
        ),
        migrations.AddField(
            model_name='portal',
            name='plan_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='plan_default_payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='plan_price_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('SI', 'Silver'), ('GO', 'Gold'), ('PL', 'Platinum')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='plan_unit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
