# Generated by Django 3.0.3 on 2021-06-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0011_auto_20210623_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='plan_currency',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='plan_price_label',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='plan_unit_amount',
        ),
        migrations.AddField(
            model_name='portal',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_plan', to='portals.PlanSubscription'),
        ),
    ]
