# Generated by Django 3.0.3 on 2021-06-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0013_portal_have_active_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='current_plan',
        ),
    ]
