# Generated by Django 3.0.3 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0014_remove_portal_current_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plansubscription',
            old_name='interval',
            new_name='plan_interval',
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='plan_users_amount',
            field=models.IntegerField(default=0),
        ),
    ]
