# Generated by Django 3.0.3 on 2021-06-30 15:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0015_auto_20210629_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmember',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='about user'),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='users/pictures/', verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='portalmember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
