# Generated by Django 3.0.3 on 2021-07-02 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portals', '0016_auto_20210630_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmember',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
