# Generated by Django 3.0.3 on 2021-07-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0017_portalmember_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmember',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
