# Generated by Django 3.0.3 on 2021-07-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0018_portalmember_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalmember',
            name='about',
        ),
        migrations.RemoveField(
            model_name='portalmember',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='portalmember',
            name='username',
        ),
        migrations.AddField(
            model_name='portalmember',
            name='initial_karma_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='notes of member'),
        ),
    ]
