# Generated by Django 3.0.3 on 2021-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0019_auto_20210703_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='administrators_count',
            new_name='active_admin_members_count',
        ),
        migrations.RenameField(
            model_name='portal',
            old_name='base_users_count',
            new_name='active_basic_members_count',
        ),
        migrations.RenameField(
            model_name='portal',
            old_name='managers_count',
            new_name='active_manager_members_count',
        ),
        migrations.RenameField(
            model_name='portal',
            old_name='users_count',
            new_name='active_members_count',
        ),
        migrations.AddField(
            model_name='portal',
            name='admin_members_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portal',
            name='basic_members_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portal',
            name='manager_members_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portal',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
