# Generated by Django 3.0.3 on 2021-07-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0020_auto_20210703_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalmember',
            name='collaborated_active_posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='collaborated_posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='collaborated_solved_posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='connections_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='created_active_posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='created_posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='created_solved_posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='followed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='invitations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='karma_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='karma_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='karma_earned_by_donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='karma_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='karma_refunded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='karma_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portalmember',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
