# Generated by Django 3.0.3 on 2021-07-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0022_auto_20210703_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='is_oficial',
            field=models.BooleanField(default=False),
        ),
    ]
