# Generated by Django 3.0.3 on 2021-07-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0023_portal_is_oficial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portalmember',
            old_name='active',
            new_name='is_active',
        ),
    ]
