# Generated by Django 3.0.3 on 2021-01-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_default_payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
