# Generated by Django 3.0.3 on 2021-03-08 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_for_withdrawal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='available_for_withdrawal_currency',
        ),
        migrations.AddField(
            model_name='earning',
            name='available_for_withdrawn_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 15, 37, 58, 247885, tzinfo=utc), help_text='Date time on pending clearance ends.', verbose_name='pending clearance expiration at'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='type',
            field=models.CharField(choices=[('OR', 'Order revenue'), ('WI', 'Withdrawn'), ('RE', 'Refund'), ('SP', 'Spent')], default='OR', max_length=2),
        ),
    ]
