# Generated by Django 3.0.3 on 2020-12-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='free_trial_expiration',
            field=models.DateTimeField(blank=True, help_text='Date time on the free tiral expiration.', null=True, verbose_name='free trial expiration at'),
        ),
    ]
