# Generated by Django 3.0.3 on 2021-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
