# Generated by Django 3.0.3 on 2021-03-19 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='available_for_withdrawn_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date time on pending clearance ends.', verbose_name='pending clearance expiration at'),
        ),
    ]
