# Generated by Django 3.0.3 on 2021-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_planpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='type',
            field=models.CharField(choices=[('OR', 'Order revenue'), ('WI', 'Withdrawn')], default='OR', max_length=2),
        ),
    ]
