# Generated by Django 3.0.3 on 2021-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210319_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
