# Generated by Django 3.0.3 on 2021-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210512_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
