# Generated by Django 3.0.3 on 2021-05-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210507_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contributed_posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
