# Generated by Django 3.0.3 on 2021-05-26 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
