# Generated by Django 3.0.3 on 2021-02-12 16:30

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_stripe_plan_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
