# Generated by Django 3.0.3 on 2021-01-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210119_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
