# Generated by Django 3.0.3 on 2020-12-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201226_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='have_active_plan',
            field=models.BooleanField(default=False, help_text='Set to true when the user have a active plan subscription.', verbose_name='have active plan subscription'),
        ),
    ]
