# Generated by Django 3.0.3 on 2021-05-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_notifications_allowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'created', 'ordering': ['karma_amount', '-created', '-modified']},
        ),
    ]
