# Generated by Django 3.0.3 on 2021-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210302_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
