# Generated by Django 3.0.3 on 2021-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210111_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_dashboard_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
