# Generated by Django 3.0.3 on 2021-03-20 13:28

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_account_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_for_withdrawal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='available_for_withdrawal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_clearance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_clearance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='reserved_for_subscriptions',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='reserved_for_subscriptions_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
