# Generated by Django 3.0.3 on 2021-02-13 12:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210212_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balance',
            new_name='net_income',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='balance_currency',
            new_name='net_income_currency',
        ),
        migrations.AddField(
            model_name='user',
            name='available_for_withdawal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='available_for_withdawal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='used_for_purchases',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='used_for_purchases_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawn',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawn_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('interval_subscription', models.CharField(choices=[('OR', 'Order revenue'), ('WI', 'Withdrawn')], max_length=2)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
