# Generated by Django 3.0.3 on 2020-12-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_current_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_view',
        ),
        migrations.AddField(
            model_name='user',
            name='seller_view',
            field=models.BooleanField(default=True, help_text='Set to true when the user view is on seller dashboard set false if is in buyer view.', verbose_name='seller view'),
        ),
    ]
