# Generated by Django 3.0.3 on 2021-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_earning_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
