# Generated by Django 3.0.3 on 2021-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210320_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='setted_to_available_for_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
