# Generated by Django 3.0.3 on 2021-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210515_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
