# Generated by Django 3.0.3 on 2021-02-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210213_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earning',
            old_name='interval_subscription',
            new_name='type',
        ),
    ]
