# Generated by Django 3.0.3 on 2021-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210315_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='available_for_withdrawn_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on pending clearance ends.', verbose_name='pending clearance expiration at'),
        ),
    ]
