# Generated by Django 3.0.3 on 2021-03-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_earning_setted_to_available_for_withdrawn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reserved_for_subscriptions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reserved_for_subscriptions_currency',
        ),
    ]
