# Generated by Django 3.0.3 on 2020-12-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201227_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='about user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller_view',
            field=models.BooleanField(default=False, help_text='Set to true when the user view is on seller dashboard set false if is in buyer view.', verbose_name='seller view'),
        ),
    ]
