# Generated by Django 3.0.3 on 2021-01-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_plansubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='current_period_end',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='to_be_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PlanSubscription',
        ),
    ]
