# Generated by Django 3.0.3 on 2021-06-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210610_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma_ratio',
            field=models.FloatField(default=0),
        ),
    ]
