# Generated by Django 3.0.3 on 2020-12-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201228_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='users/pictures/', verbose_name='profile picture'),
        ),
    ]
