# Generated by Django 3.0.3 on 2021-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_karma_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portals_count',
            field=models.IntegerField(default=0),
        ),
    ]
