# Generated by Django 3.0.3 on 2021-06-19 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_auto_20210619_1300'),
        ('users', '0008_user_portals_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginactivity',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.Portal'),
        ),
        migrations.AlterField(
            model_name='userloginactivity',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
