# Generated by Django 3.0.3 on 2021-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_active_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages_notificatoin_sent',
            field=models.BooleanField(default=False),
        ),
    ]
