# Generated by Django 3.0.3 on 2021-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_messages_notificatoin_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_dashboard_url',
        ),
        migrations.AddField(
            model_name='user',
            name='paypal_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
