# Generated by Django 3.0.3 on 2021-06-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_auto_20210622_1511'),
        ('users', '0009_auto_20210619_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.Portal'),
        ),
        migrations.AddField(
            model_name='earning',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.Portal'),
        ),
        migrations.AddField(
            model_name='karmaearning',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.Portal'),
        ),
        migrations.AddField(
            model_name='review',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portals.Portal'),
        ),
    ]
