# Generated by Django 3.0.3 on 2021-07-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210622_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma_earned_by_donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='karma_refunded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='karmaearning',
            name='type',
            field=models.CharField(choices=[('RE', 'Refunded'), ('ED', 'Earned by donation'), ('EA', 'Earned'), ('SP', 'Spent')], max_length=2),
        ),
    ]
