# Generated by Django 3.0.3 on 2021-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='anonymous_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
