# Generated by Django 3.0.3 on 2021-05-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_anonymous_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='anonymous_email',
            new_name='email',
        ),
    ]
