# Generated by Django 3.0.3 on 2021-03-30 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionactivity',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Revision'),
        ),
        migrations.AddField(
            model_name='requesttohelpactivity',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
        migrations.AddField(
            model_name='requesttohelpactivity',
            name='request_to_help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.RequestToHelp'),
        ),
        migrations.AddField(
            model_name='deliveryactivity',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
        migrations.AddField(
            model_name='deliveryactivity',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Delivery'),
        ),
        migrations.AddField(
            model_name='cancelorderactivity',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activity'),
        ),
        migrations.AddField(
            model_name='cancelorderactivity',
            name='cancel_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CancelOrder'),
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
