# Generated by Django 3.0.3 on 2021-02-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_offer'),
        ('activities', '0002_auto_20210215_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryactivity',
            name='increase_amount',
        ),
        migrations.AddField(
            model_name='deliveryactivity',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Delivery'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('OF', 'Offer order'), ('CT', 'Change delivery time order'), ('IA', 'Increase order amount'), ('DE', 'Delivery order'), ('RE', 'Revision order'), ('CA', 'Delivery order')], max_length=2),
        ),
    ]
