# Generated by Django 3.0.3 on 2021-01-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20210126_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorderactivity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cancelorderactivity',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='cancelorderactivity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='changedeliverytimeactivity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='changedeliverytimeactivity',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='changedeliverytimeactivity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deliveryactivity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='deliveryactivity',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='deliveryactivity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='increaseamountactivity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='increaseamountactivity',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='increaseamountactivity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='offeractivity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='offeractivity',
            name='closed',
        ),
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offeractivity',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendent'), ('AC', 'Accepted')], default='PE', max_length=2),
        ),
    ]
