# Generated by Django 3.0.3 on 2021-02-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20210219_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryactivity',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendent'), ('AC', 'Accepted')], default='PE', max_length=2),
        ),
    ]
