# Generated by Django 3.0.3 on 2021-02-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210213_1244'),
        ('activities', '0003_auto_20210213_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyreceivedactivity',
            name='offer',
        ),
        migrations.AddField(
            model_name='moneyreceivedactivity',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
