# Generated by Django 3.0.3 on 2021-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_deliveryactivity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorderactivity',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendent'), ('AC', 'Accepted')], default='PE', max_length=2),
        ),
    ]
