# Generated by Django 3.0.3 on 2021-02-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210213_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('OF', 'Offer order'), ('CT', 'Change delivery time order'), ('IA', 'Increase amount order'), ('DE', 'Delivery order'), ('RE', 'Revision order'), ('CA', 'Delivery order')], max_length=2),
        ),
        migrations.DeleteModel(
            name='MoneyReceivedActivity',
        ),
    ]
