# Generated by Django 3.0.3 on 2021-02-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_cancelorderactivity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelorderactivity',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendent'), ('AC', 'Accepted'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
    ]
