# Generated by Django 3.0.3 on 2021-06-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['unit_amount']},
        ),
    ]
