# Generated by Django 3.0.3 on 2021-06-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('MO', 'Monthly'), ('YE', 'Yearly')], default='MO', max_length=2),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('SI', 'Silver'), ('GO', 'Gold'), ('PL', 'Platinum')], max_length=2),
        ),
    ]
