# Generated by Django 3.0.3 on 2021-05-06 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20210501_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestToContribute',
            new_name='ContributeRequest',
        ),
    ]
