# Generated by Django 3.0.3 on 2021-05-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210506_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributerequest',
            name='is_accepted',
        ),
    ]
