# Generated by Django 3.0.3 on 2021-04-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210429_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='admin',
            new_name='user',
        ),
    ]
