# Generated by Django 3.0.3 on 2021-05-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210510_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
