# Generated by Django 3.0.3 on 2021-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_shared_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='karma_offered',
            field=models.IntegerField(default=100),
        ),
    ]
