# Generated by Django 3.0.3 on 2021-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_contributerequest_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
