# Generated by Django 3.0.3 on 2021-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210512_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmember',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmember',
            name='reputation',
            field=models.FloatField(default=0.0),
        ),
    ]
