# Generated by Django 3.0.3 on 2021-06-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_kanbancard_kanbanlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='drawing',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='posts/drawings/', verbose_name='posts drawings'),
        ),
    ]
