# Generated by Django 3.0.3 on 2021-06-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='drawing',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='posts/drawings/', verbose_name='Drawing File'),
        ),
    ]
