# Generated by Django 3.0.3 on 2021-05-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210513_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmember',
            old_name='reputation',
            new_name='rate',
        ),
    ]
