# Generated by Django 3.0.3 on 2021-05-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210513_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmember',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
