# Generated by Django 3.0.3 on 2021-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postfile_postfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files_size',
            field=models.IntegerField(default=0),
        ),
    ]
