# Generated by Django 3.0.3 on 2021-05-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_draft_solution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmember',
            old_name='comment',
            new_name='draft_comment',
        ),
        migrations.RenameField(
            model_name='postmember',
            old_name='rate',
            new_name='draft_rating',
        ),
    ]
