# Generated by Django 3.0.3 on 2021-06-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postfile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='posts/resources/files/'),
        ),
    ]
