# Generated by Django 3.0.3 on 2021-02-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210215_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='service_fee_currency',
        ),
    ]
