# Generated by Django 3.0.3 on 2021-03-22 17:21

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210319_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credits_reserved',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credits_reserved_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
