# Generated by Django 3.0.3 on 2021-01-30 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20210129_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='total_amount',
            new_name='unit_amount',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='total_amount_currency',
            new_name='unit_amount_currency',
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('unit_amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('type', models.CharField(choices=[('NO', 'Two payments order'), ('TP', 'Two payments order'), ('RO', 'Recurrent order')], max_length=2)),
                ('interval_subscription', models.CharField(choices=[('AN', 'Annual'), ('MO', 'Month')], default='MO', max_length=2)),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('to_be_cancelled', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('payment_issue', models.BooleanField(default=False)),
                ('current_period_end', models.IntegerField(blank=True, default=0)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_buyer', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='orders.Order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
