# Generated by Django 3.0.3 on 2021-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210207_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbilling',
            name='refounded',
            field=models.BooleanField(default=False),
        ),
    ]
