# Generated by Django 3.0.3 on 2021-01-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210124_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='first_payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
