# Generated by Django 3.0.3 on 2021-01-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210127_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('NO', 'Two payments order'), ('TP', 'Two payments order'), ('RO', 'Recurrent order')], max_length=2),
        ),
    ]
