# Generated by Django 3.0.3 on 2021-01-31 12:08

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210130_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_payment',
            new_name='payment_at_delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_payment_currency',
            new_name='payment_at_delivery_currency',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='unit_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount_currency',
            new_name='unit_amount_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='interval_subscription',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='due_to_seller',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='due_to_seller_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='first_payment_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('amount_paid', models.FloatField()),
                ('amount_paid_usd_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('amount_paid_usd', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('paid', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice', to='orders.Order')),
                ('order_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_invoice', to='orders.OrderPayment')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
