# Generated by Django 3.0.3 on 2021-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderbilling_refounded'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbilling',
            name='charge_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
