# Generated by Django 3.0.3 on 2021-03-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210322_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='credits_reserved',
        ),
        migrations.RemoveField(
            model_name='order',
            name='credits_reserved_currency',
        ),
    ]
