# Generated by Django 3.0.3 on 2021-02-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderbilling_charge_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbilling',
            old_name='refounded',
            new_name='refunded',
        ),
    ]
