# Generated by Django 3.0.3 on 2021-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210124_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
    ]
