# Generated by Django 3.0.3 on 2021-01-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210131_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='invoice_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='service_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='interval_subscription',
            field=models.CharField(choices=[('AN', 'Year'), ('MO', 'Month')], default='MO', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='interval_subscription',
            field=models.CharField(choices=[('AN', 'Year'), ('MO', 'Month')], default='MO', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='orders.Order'),
        ),
    ]
