# Generated by Django 3.0.3 on 2021-01-31 15:57

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210131_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('service_fee', models.FloatField(blank=True, null=True)),
                ('due_to_seller_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('due_to_seller', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True)),
                ('first_payment_paid', models.BooleanField(default=True)),
                ('payment_at_delivery', models.FloatField()),
                ('payment_at_delivery_currency', models.CharField(max_length=3)),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('to_be_cancelled', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('payment_issue', models.BooleanField(default=False)),
                ('current_period_end', models.IntegerField(blank=True, default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing', to='orders.Order')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='order_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing_invoice', to='orders.OrderBilling'),
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
