# Generated by Django 3.0.3 on 2021-02-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210219_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='description',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='amount_increased',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='increase_amount',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='issued_by',
        ),
    ]
