# Generated by Django 3.0.3 on 2021-01-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210124_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='is_split_payment',
            new_name='two_payments_order',
        ),
    ]
