# Generated by Django 3.0.3 on 2021-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210131_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='rate_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
