# Generated by Django 3.0.3 on 2021-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210219_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='modification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
