# Generated by Django 3.0.3 on 2021-02-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210207_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_paid_currency',
        ),
    ]
