# Generated by Django 3.0.3 on 2021-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_offer_rate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
