# Generated by Django 3.0.3 on 2021-02-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delivery_modification_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorder',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
