# Generated by Django 3.0.3 on 2021-02-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cancelorder_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorder',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
