# Generated by Django 3.0.3 on 2021-02-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210209_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_payment_paid',
        ),
    ]
