# Generated by Django 3.0.3 on 2021-02-13 11:44

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_first_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='service_fee',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='service_fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
