# Generated by Django 3.0.3 on 2021-02-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cancelorder_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelorder',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='cancelorder',
            name='cancelled',
        ),
        migrations.AddField(
            model_name='cancelorder',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendent'), ('AC', 'Accepted'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
    ]
