# Generated by Django 3.0.3 on 2021-02-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_revision_issued_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='modification_requested',
        ),
    ]
