# Generated by Django 3.0.3 on 2021-02-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_delivery_modification_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_at_delivery_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
