from django.core.management.base import BaseCommand
from api.plans.models import Plan


class Command(BaseCommand):

    def handle(self, *args, **options):

        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=12.50,
            currency="EUR",
            price_label="12.50€"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=14.90,
            currency="USD",
            price_label="$14.90"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=19.90,
            currency="AUD",
            price_label="$19.90"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=79.90,
            currency="BRL",
            price_label="R$79.90"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=18.90,
            currency="CAD",
            price_label="R$18.90"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=12.50,
            currency="GBP",
            price_label="£12.50"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=22000000.00,
            currency="IDR",
            price_label="Rp22000000.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=49.90,
            currency="ILS",
            price_label="₪49.90"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=1100.00,
            currency="INR",
            price_label="₹1100.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=1700.00,
            currency="JPY",
            price_label="¥1700.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=1700000.00,
            currency="KRW",
            price_label="₩1700000.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=300.00,
            currency="MXN",
            price_label="$300.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=130.00,
            currency="NOK",
            price_label="130.00kr"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=59.90,
            currency="PLN",
            price_label="59.90zł"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=1100.00,
            currency="RUB",
            price_label="₽1100.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=19.90,
            currency="SGD",
            price_label="$19.90"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=460.00,
            currency="THB",
            price_label="฿460.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=109.00,
            currency="TRY",
            price_label="₺109.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=425.00,
            currency="TWD",
            price_label="₺425.00"
        )
        Plan.objects.create(
            type=Plan.BASIC,
            unit_amount=219.00,
            currency="ZAR",
            price_label="₺219.00"
        )
        print("Plans created")
